services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development 
    restart: always
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: ${DOCKERHUB_USERNAME}/backend:latest
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./logs:/usr/src/app/logs:rw
      - ./uploads:/usr/src/app/uploads:rw
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - chat-network

  redis:
    image: redis:alpine
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/usr/src/app/uploads:ro
    depends_on:
      - backend
      - frontend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  redis-data: