services:
  frontend:
    build:
      context: ./frontend
      target: production 
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      target: production
    deploy:
      replicas: 2 
    ports:
      - "4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - REDIS_HOST=redis
    volumes:
      - ${PWD}/logs:/usr/src/app/logs:rw
      - ${PWD}/uploads:/usr/src/app/uploads:rw
    command: node dist/main 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx